### ISSUE TITLE
唉，TypeScript，提高阅读成本

### ISSUE THREAD

**Issue by x-da** [alipay/alipay-sdk#6]
头疼，还要折腾TypeScript的环境

**Comment by tudou527** [comment]
看 readme 的文档不是更方便 ?

**Comment by atian25** [comment]
他的意思估计是，文档都是 ts 的写法的

**Comment by x-da** [comment]
感谢两位回复，typeScript这块了解的不多，没其他冒犯的意思。

**Comment by x-da** [comment]
const AlipaySdk = require('alipay-sdk').default;
	const Ali = new AlipaySdk({
		appId: '2018082461*****',
		privateKey: fs.readFileSync('./cert/rsa_private_key.pem', 'ascii'),
		alipayPublicKey: fs.readFileSync('./cert/rsa_public_key.pem', 'ascii'),
	});

	Ali.exec('alipay.system.oauth.token', {
		grantType: 'authorization_code',
		code: 'code'
	},{validateSign: true}).catch(function(err){
		console.log(err);
	});
分享一下 JS写法
